version: 0.0
os: linux
files:
 - source: ./
   destination: /home/ubuntu/app
hooks:
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
  ValidateService:
   - location: scripts/check_server
     timeout: 300
     runas: root
